name: prise-build-samples-plugins

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
  
    - name: Build Samples
      run: dotnet build samples/Plugins/Plugins.sln