name: publish-packages

on: 
  workflow_dispatch:
    inputs:
      priseversion:
        description: 'Prise Version'
        default: '2.0.0'
        required: true
      proxyversion:
        description: 'Prise.Proxy Version'
        default: '2.0.0'
        required: true
      pluginversion:
        description: 'Prise.Plugin Version'
        default: '2.0.0'
        required: true
      reverseproxyversion:
        description: 'Prise.ReverseProxy Version'
        default: '2.0.0'
        required: true
      mvcversion:
        description: 'Prise.Mvc Version'
        default: '2.0.0'
        required: true
      testingversion:
        description: 'Prise.Testing Version'
        default: '2.0.0'
        required: true
      nugetKey:
        description: 'Nuget Api Key'
        required: true
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        
    - name: Build Prise
      run: dotnet build src/Prise/Prise.csproj --configuration Release -f net5.0
    - name: Build Prise with netcoreapp2.1
      run: dotnet build src/Prise/Prise.csproj --configuration Release -f netcoreapp2.1
    - name: Build Prise with netcoreapp3.1
      run: dotnet build src/Prise/Prise.csproj --configuration Release -f netcoreapp3.1
