name: publish-packages

on: 
  workflow_dispatch:
    inputs:
      priseversion:
        description: 'Prise Version'
        default: '2.0.0'
        required: true
      proxyversion:
        description: 'Prise.Proxy Version'
        default: '2.0.0'
        required: true
      pluginversion:
        description: 'Prise.Plugin Version'
        default: '2.0.0'
        required: true
      reverseproxyversion:
        description: 'Prise.ReverseProxy Version'
        default: '2.0.0'
        required: true
      mvcversion:
        description: 'Prise.Mvc Version'
        default: '2.0.0'
        required: true
      testingversion:
        description: 'Prise.Testing Version'
        default: '2.0.0'
        required: true
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        
    - name: Build Prise
      run: dotnet build src/Prise/Prise.csproj --configuration Release -f net5.0
    - name: Build Prise with netcoreapp2.1
      run: dotnet build src/Prise/Prise.csproj --configuration Release -f netcoreapp2.1
    - name: Build Prise with netcoreapp3.1
      run: dotnet build src/Prise/Prise.csproj --configuration Release -f netcoreapp3.1

    - name: Build Prise.Mvc
      run: dotnet build src/Prise.Mvc/Prise.Mvc.csproj --configuration Release -f net5.0
    - name: Build Prise.Mvc with netcoreapp2.1
      run: dotnet build src/Prise.Mvc/Prise.Mvc.csproj --configuration Release -f netcoreapp2.1
    - name: Build Prise.Mvc with netcoreapp3.1
      run: dotnet build src/Prise.Mvc/Prise.Mvc.csproj --configuration Release -f netcoreapp3.1
        
    - name: Build Prise.Plugin with netstandard2.0
      run: dotnet build src/Prise.Plugin/Prise.Plugin.csproj --configuration Release -f netstandard2.0
      
    - name: Build Prise.Proxy with netstandard2.0
      run: dotnet build src/Prise.Proxy/Prise.Proxy.csproj --configuration Release -f netstandard2.0
      
    - name: Build Prise.ReverseProxy with netstandard2.0
      run: dotnet build src/Prise.ReverseProxy/Prise.ReverseProxy.csproj --configuration Release -f netstandard2.0
    
    - name: Push Prise
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/Prise/Prise.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        VERSION_STATIC: ${{github.event.inputs.priseversion}}    